language: go
go:
  - 1.12.x
os:
  - linux
dist: xenial
sudo: false
install: true
env:
  - GO111MODULE=on
script:
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic
after_success:
  - base <(curl -s https://codecov.io/bash)