apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raftapp.fullname" . }}
  labels:
{{ include "raftapp.labels" . | indent 4 }}
data:
{{(tpl (.Files.Glob "resources/cfg/*").AsConfig . | indent 2)}}
