apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "raftapp.fullname" . }}
  labels:
{{ include "raftapp.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
