apiVersion: v1
kind: Service
metadata:
  name: {{ include "raftapp.fullname" . }}
  labels:
{{ include "raftapp.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metrics.port }}
      targetPort: http
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.raft.port }}
      targetPort: raft
      protocol: TCP
      name: raft
  selector:
    app.kubernetes.io/name: {{ include "raftapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
