{
 "title": "Raft Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Raft Role: $job",
   "type": "gauge",
   "description": "Last sampled Raft role of an instance.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "repeat": "job",
   "targets": [
    {
     "expr": "raftapp_raft_role{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Raft Role: $job",
   "type": "gauge",
   "description": "Last sampled Raft role of an instance.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "raftapp_raft_role{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Raft Role: $job",
   "type": "gauge",
   "description": "Last sampled Raft role of an instance.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "raftapp_raft_role{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Leader for $job",
   "type": "singlestat",
   "description": "Local  perspective of who is Raft leader.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "raftapp_raft_leader{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Leader for $job",
   "type": "singlestat",
   "description": "Local  perspective of who is Raft leader.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "raftapp_raft_leader{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Leader for $job",
   "type": "singlestat",
   "description": "Local  perspective of who is Raft leader.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "raftapp_raft_leader{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Term at $job",
   "type": "graph",
   "description": "Raft Term",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "repeat": "job",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_term{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Term at $job",
   "type": "graph",
   "description": "Raft Term",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_term{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Term at $job",
   "type": "graph",
   "description": "Raft Term",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_term{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Committed Index at $job",
   "type": "graph",
   "description": "Raft Committed Index",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "repeat": "job",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_committedIndex{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Committed Index at $job",
   "type": "graph",
   "description": "Raft Committed Index",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_committedIndex{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Committed Index at $job",
   "type": "graph",
   "description": "Raft Committed Index",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_committedIndex{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Applied Index at $job",
   "type": "graph",
   "description": "Raft Applied Index",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "repeat": "job",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_lastApplied{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Applied Index at $job",
   "type": "graph",
   "description": "Raft Applied Index",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_lastApplied{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Applied Index at $job",
   "type": "graph",
   "description": "Raft Applied Index",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "raftapp_raft_lastApplied{job=\"$job\"}"
    }
   ]
  }
 ]
}